 {
     "button":[
     {	
          "type":"view",
          "name":"帮手列表",
          "url":"http://zbfirst.com/list.php"
      },
      {
           "name":"休闲游戏",
           "sub_button":[
           {	
               "type":"view",
               "name":"刮刮乐",
               "url":"http://zbfirst.com/game/guaguaka.php"
            },
            {
               "type":"view",
               "name":"我画你猜",
               "url":"http://zbfirst.com/game/wohuanicai.php"
            },
            {
               "type":"view",
               "name":"摇一摇",
               "url":"http://zbfirst.com/game/yaoyiyao.php"
            },
            {
               "type":"view",
               "name":"2048",
               "url":"http://zbfirst.com/game/2048"
            },
            {
               "type":"view",
               "name":"飞翔的小鸟",
               "url":"http://zbfirst.com/game/flybird"
            }]
       },
      {
           "name":"帮手社区",
           "sub_button":[
           {	
               "type":"view",
               "name":"意见反馈",
               "url":"http://zbfirst.com/bbs/contact.php"
            },
            {
               "type":"view",
               "name":"交流社区",
               "url":"http://zbfirst.com/bbs/"
            },
            {
               "type":"view",
               "name":"关于我们",
               "url":"http://zbfirst.com/bbs/aboutus.php"
            }]
       }]
 }